apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 168h
  name: policy-exc-req-s4852x2619i-0
spec:
  exceptions:
  - policyName: disallow-privilege-escalation
    ruleNames:
    - autogen-privilege-escalation
    - privilege-escalation
  - policyName: require-run-as-nonroot
    ruleNames:
    - autogen-run-as-non-root
    - run-as-non-root
  - policyName: disallow-capabilities-strict
    ruleNames:
    - require-drop-all
    - autogen-require-drop-all
  match:
    any:
    - resources:
        kinds:
        - Pod
        names:
        - local-path-provisioner-988d74bc-txjmp
        namespaces:
        - local-path-storage
    - resources:
        kinds:
        - Deployment
        names:
        - local-path-provisioner
        namespaces:
        - local-path-storage
    - resources:
        kinds:
        - ReplicaSet
        names:
        - local-path-provisioner-988d74bc
        namespaces:
        - local-path-storage
