apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2024-08-13T114344Z
  name: policy-exc-req-q8442c5941p-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: restrict-automount-sa-token
    ruleNames:
    - validate-automountServiceAccountToken
    - autogen-validate-automountServiceAccountToken
  match:
    any:
    - resources:
        kinds:
        - Job
        names:
        - kyverno-cleanup-cluster-admission-reports-28715740
        - kyverno-cleanup-cluster-admission-reports-28715680
        - kyverno-cleanup-admission-reports-28715740
        namespaces:
        - kyverno
    - resources:
        kinds:
        - ReplicaSet
        names:
        - kyverno-background-controller-6c6fb7744f
        - kyverno-cleanup-controller-6cf4bcdd4d
        - kyverno-admission-controller-fc66cc889
        - kyverno-reports-controller-7ddd547fdf
        namespaces:
        - kyverno
    - resources:
        kinds:
        - Pod
        names:
        - kyverno-cleanup-cluster-admission-reports-28715740-zxvbd
        - kyverno-cleanup-controller-6cf4bcdd4d-bh9d8
        - kyverno-background-controller-6c6fb7744f-kh5dc
        - kyverno-cleanup-admission-reports-28715740-2z9w2
        - kyverno-admission-controller-fc66cc889-8nwnj
        - kyverno-reports-controller-7ddd547fdf-sp82x
        - kyverno-admission-controller-fc66cc889-68578
        - kyverno-admission-controller-fc66cc889-qr2kh
        namespaces:
        - kyverno
    - resources:
        kinds:
        - Deployment
        names:
        - kyverno-background-controller
        - kyverno-admission-controller
        - kyverno-reports-controller
        - kyverno-cleanup-controller
        namespaces:
        - kyverno
